[package]
name = "stm-cli"
version = "1.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
stm-core = { path = "../stm-core" }
stm-writer = { path = "../stm-writer" }
stm-parser = { path = "../stm-parser" }
stm-signature = { path = "../stm-signature" }
stm-file = { path = "../stm-file" }
stm-stream = { path = "../stm-stream" }